on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep hello | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace hello`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: hello
        container-registry-url: rbacr001.azurecr.io
        container-registry-username: ${{ secrets.acr_rbacr_username }}
        container-registry-password: ${{ secrets.acr_rbacr_password }}
        secret-name: rbk8stestdockerauth
       
    - uses: rachitb777/k8s-deploy@rbtrac1
      with:
        namespace: hello
        manifests: |
          yaml/hello-kubernetes.yaml
        images: |
          rbacr001.azurecr.io/rbpetest:${{ github.sha }}
        imagepullsecrets: |
          rbk8stestdockerauth