on: [workflow_dispatch]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_rbk8s_kubeConfig }}
      id: login        
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep hello-new | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace hello-new`
        fi
        
    - uses: azure/k8s-create-secret@v1
      with:
        namespace: hello-new
        container-registry-url: rbacr001.azurecr.io
        container-registry-username: ${{ secrets.acr_rbacr_username }}
        container-registry-password: ${{ secrets.acr_rbacr_password }}
        secret-name: rbk8stestdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: hello-new
        manifests: |
          yaml/hello-kubernetes.yaml
        images: |
          rbacr001.azurecr.io/rbpetest:${{ github.sha }}
        imagepullsecrets: |
          rbk8stestdockerauth